app:
  image: $IMAGE_NAME
  ports:
    - 8443:8443
  volumes:
    - ../:/app
  env_file: ../.env.development
  command: npm run dev
  links:
    - postgres

postgres:
  image: $IMAGE_NAME-db1
  ports:
    - 5432:5432